apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.bindingSubscriber.name }}
spec:
  type: bindings.azure.blobstorage
  metadata:
  - name: storageAccount
    value: "{{ .Values.bindingSubscriber.storageAccount }}"
  - name: storageAccessKey
    secretKeyRef:
        name: {{ .Values.bindingSubscriber.storageAccessKey }}
        key: {{ .Values.bindingSubscriber.storageAccessKey }}
  - name: container
    value: "{{ .Values.bindingSubscriber.container }}"
scopes:
  {{- range $scope := .Values.bindingSubscriber.scopes }}
  - {{ $scope }}
  {{- end }}
auth:
  secretStore: {{ .Values.secretStore.name }}