apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.pubsub.name }}
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    secretKeyRef:
        name: {{ .Values.pubsub.connectionString }}
        key: {{ .Values.pubsub.connectionString }}
scopes:
  {{- range $scope := .Values.pubsub.scopes }}
  - {{ $scope }}
  {{- end }}
auth:
  secretStore: {{ .Values.secretStore.name }}