# Default values for retropos-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 2
  aadpodidbinding: kubernetes.azureidentity
  name: publisher-api
  dapr:
    name: publisher-api
    config: dapr.tracing
  containerName: publisher-api
  image:
    repository: 
    pullPolicy: Always 
  env:
    environment: Production
    pubSubComponentName: dapr.pubsub
    pubSubTopicName: message-topic
resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "150Mi"
    cpu: "150m"
service:
  name: publisher-api
  type: LoadBalancer
autoscaling:
  name: publisher-api
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 40