# Default values for retropos-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 5
  aadpodidbinding: kubernetes.azureidentity
  name: subscriber-api
  dapr:
    name: subscriber-api
    config: dapr.tracing
  containerName: subscriber-api
  image:
    repository: 
    pullPolicy: Always
  env:
    environment: Production
    pubSubComponentName: dapr.pubsub
    pubSubTopicName: message-topic
    outputBindingComponentName: dapr.binding.subscriber
    serviceBusConnectionString: 
  resources:
    requests:
      memory: "200Mi"
      cpu: "150m"
    limits:
      memory: "300Mi"
      cpu: "200m"
keda:
  triggerAuthentication:
    name: keda.triggerauthentication.subscriber-api
  scaledObject:
    name: keda.scaledobject.subscriber-api
    deploymentName: subscriber-api
    pollingInterval: 5
    coolDownPeriod: 0
    minReplicaCount: 5
    maxReplicaCount: 20
    triggers:
      type: azure-servicebus
      topicName: message-topic
      subscriptionName: subscriber-api
      messageCount: 2
      authenticationRef: keda.triggerauthentication.subscriber-api
secretProviderClass:
  name: secretproviderclass.keyvault