# Default values for retropos-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 2
  aadpodidbinding: kubernetes.azureidentity
  name: exposed-api
  dapr:
    name: exposed-api
    config: dapr.tracing
  containerName: exposed-api
  image:
    repository: 
    pullPolicy: Always 
  env:
    environment: Production
    outputBindingComponentName: dapr.binding.internal-queue
resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "150Mi"
    cpu: "150m"
service:
  name: exposed-api
  type: LoadBalancer
autoscaling:
  name: exposed-api
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 40